spin_manifest_version = 2

[application]
name = "hello-spin"
version = "0.1.0"
authors = ["carl <carlpaolino05@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "hello-spin"

[component.hello-spin]
source = "target/wasm32-wasip1/release/hello_spin.wasm"
allowed_outbound_hosts = []
[component.hello-spin.build]
command = "cargo build --target wasm32-wasip1 --release"
watch = ["src/**/*.rs", "Cargo.toml"]
